# Generated by Django 4.2.14 on 2024-10-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_local_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local_Company',
        ),
    ]
