# Generated by Django 5.2.8 on 2026-02-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_delete_local_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaders',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
