# Generated by Django 4.2.14 on 2024-10-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_delete_local_company'),
        ('service', '0009_factorysetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local_Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('factory_address', models.CharField(blank=True, max_length=1024, null=True)),
                ('head_office_address', models.CharField(blank=True, max_length=1024, null=True)),
                ('website_address', models.CharField(blank=True, max_length=200, null=True)),
                ('managing_director', models.CharField(blank=True, max_length=255, null=True)),
                ('business_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('product_line', models.CharField(blank=True, max_length=1024, null=True)),
                ('number_of_manpower', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_finishing_line', models.CharField(blank=True, max_length=255, null=True)),
                ('production_capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('social_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('export_country', models.CharField(blank=True, max_length=255, null=True)),
                ('major_buyer', models.CharField(blank=True, max_length=255, null=True)),
                ('production_area', models.CharField(blank=True, max_length=1024, null=True)),
                ('other_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('establishment_year', models.CharField(blank=True, max_length=4, null=True)),
                ('bond_license_status', models.CharField(blank=True, max_length=100, null=True)),
                ('investment', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.type')),
            ],
        ),
    ]
