# Generated by Django 4.2.14 on 2024-10-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_local_factory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local_Factory',
        ),
    ]
