# Generated by Django 5.2.8 on 2026-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0013_local_factory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
