# Generated by Django 5.2.8 on 2026-02-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0014_companystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='partners/')),
            ],
        ),
    ]
