# Generated by Django 5.2.8 on 2026-02-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0015_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='company_profiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
