# Generated by Django 5.2.8 on 2026-02-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_resume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='circular',
            field=models.FileField(blank=True, null=True, upload_to='job_circulars/'),
        ),
    ]
