# Generated by Django 5.0 on 2026-03-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_student_semesterresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('sgpa', models.FloatField(blank=True, null=True)),
                ('average_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('final_cgpa', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('reg_no', 'semester')},
            },
        ),
    ]
